export const SET_LOCATION = 'SET_LOCATION';
export const TOGGLE_FILTERS = 'TOGGLE_FILTERS';
export const TOGGLE_PICKAGAIN = 'TOGGLE_PICKAGAIN';
export const REQUEST_LOCATION_DETAILS = 'REQUEST_LOCATION_DETAILS';
export const RECEIVED_LOCATION_DETAILS = 'RECEIVED_LOCATION_DETAILS';
export const SET_LOCATION_DETAILS = 'SET_LOCATION_DETAILS';