// Set Location from Random Selection Action Type
export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';

// Location Details Action Types
export const FETCH_LOCATION_DETAILS_REQUEST = 'FETCH_LOCATION_DETAILS_REQUEST';
export const FETCH_LOCATION_DETAILS_SUCCESS = 'FETCH_LOCATION_DETAILS_SUCCESS';
export const FETCH_LOCATION_DETAILS_FAILURE = 'FETCH_LOCATION_DETAILS_FAILURE';

// Reviews Action Types
export const FETCH_REVIEWS_REQUEST = 'FETCH_REVIEWS_REQUEST';
export const FETCH_REVIEWS_SUCCESS = 'FETCH_REVIEWS_SUCCESS';
export const FETCH_REVIEWS_FAILURE = 'FETCH_REVIEWS_FAILURE';

// UI Action Types
export const TOGGLE_FILTERS = 'TOGGLE_FILTERS';
export const TOGGLE_PICKAGAIN = 'TOGGLE_PICKAGAIN';